"""
Abstract base class for trading strategies.

All strategies must inherit from BaseStrategy and implement the required methods.
This ensures consistent interfaces across different strategy implementations.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import date
from typing import Dict, List, Optional, Any
from enum import Enum

import pandas as pd


class SignalType(Enum):
    """Trading signal types."""
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.

    Attributes:
        date: Date the signal was generated
        symbol: Target symbol
        signal_type: BUY, SELL, or HOLD
        strength: Signal strength (0-1), used for position sizing
        metadata: Additional signal information
    """
    date: date
    symbol: str
    signal_type: SignalType
    strength: float = 1.0
    metadata: Optional[Dict[str, Any]] = None

    def __post_init__(self):
        if not 0 <= self.strength <= 1:
            raise ValueError(f"Signal strength must be between 0 and 1, got {self.strength}")


@dataclass
class BacktestParams:
    """
    Parameters for backtesting a strategy.

    Attributes:
        start_date: Backtest start date
        end_date: Backtest end date
        initial_capital: Starting capital
        rebalance_frequency: How often to rebalance ('daily', 'weekly', 'monthly')
        transaction_cost_bps: Transaction cost in basis points
        slippage_bps: Slippage estimate in basis points
    """
    start_date: str
    end_date: str
    initial_capital: float = 10000.0
    rebalance_frequency: str = "monthly"
    transaction_cost_bps: int = 10
    slippage_bps: int = 10


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must implement:
    - generate_signals(): Generate trading signals from market data
    - calculate_position_size(): Determine position size for a signal
    - get_backtest_params(): Return default backtesting parameters

    Attributes:
        name: Strategy name
        universe: List of symbols this strategy trades
    """

    def __init__(self, name: str, universe: List[str]):
        """
        Initialize the strategy.

        Args:
            name: Strategy identifier
            universe: List of tradeable symbols
        """
        self.name = name
        self.universe = [s.upper() for s in universe]

    @abstractmethod
    def generate_signals(self, data: Dict[str, pd.DataFrame]) -> List[Signal]:
        """
        Generate trading signals from market data.

        This is the core strategy logic. Implementations should analyze
        the provided market data and return a list of trading signals.

        Args:
            data: Dict mapping symbol to DataFrame with OHLCV data.
                  DataFrames have DatetimeIndex and columns: open, high, low, close, volume

        Returns:
            List of Signal objects representing trading decisions

        Note:
            - Must not use future data (look-ahead bias)
            - Should handle missing data gracefully
            - Should be deterministic for the same input
        """
        pass

    @abstractmethod
    def calculate_position_size(
        self,
        signal: Signal,
        portfolio_value: float,
        current_positions: Dict[str, float]
    ) -> float:
        """
        Calculate position size for a signal.

        Args:
            signal: The trading signal
            portfolio_value: Current total portfolio value
            current_positions: Dict mapping symbol to current position value

        Returns:
            Target position size in dollars (positive for long, negative for short)

        Note:
            - Must respect risk limits (max position size, sector limits)
            - Should consider current positions to avoid over-concentration
        """
        pass

    @abstractmethod
    def get_backtest_params(self) -> BacktestParams:
        """
        Return default backtesting parameters for this strategy.

        Returns:
            BacktestParams with strategy-specific defaults
        """
        pass

    def validate_data(self, data: Dict[str, pd.DataFrame]) -> bool:
        """
        Validate that input data meets strategy requirements.

        Args:
            data: Market data dict

        Returns:
            True if data is valid, False otherwise

        Raises:
            ValueError: If data is invalid with explanation
        """
        if not data:
            raise ValueError("No data provided")

        for symbol in self.universe:
            if symbol not in data:
                raise ValueError(f"Missing data for required symbol: {symbol}")

            df = data[symbol]
            if df.empty:
                raise ValueError(f"Empty DataFrame for symbol: {symbol}")

            required_columns = {"open", "high", "low", "close", "volume"}
            missing = required_columns - set(df.columns)
            if missing:
                raise ValueError(f"Missing columns for {symbol}: {missing}")

        return True

    def get_required_history(self) -> int:
        """
        Return number of historical days needed for signal generation.

        Override in subclasses if strategy needs specific lookback period.

        Returns:
            Number of trading days of history required
        """
        return 252  # Default: 1 year

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name='{self.name}', universe={self.universe})"
